### ISSUE TITLE
Incomplete code of class `Whole_Slide_Bag_FP_SAVE` in `extract_topK_ROIs.py`

### ISSUE THREAD

**Issue by caiyu6666** [invoker-LL/WSI-finetuning#3]
Hello, thank you for your code. However, I met some problem in Stage-2 (wsi-finetuning with topK).

In `extract_topK_ROIs.py` line 88, 
```python
dataset = Whole_Slide_Bag_FP_SAVE(file_path=patch_file_path,wsi=wsi,select_idx=topk_indexes)
```

However, the class `Whole_Slide_Bag_FP_SAVE` doesn't have the keyword argument `select_idx`. Could you please provide the complete code?
Thanks a lot!

**Comment by MrPeterJin** [comment]
I was encountering the same problem. Is there any update?

**Comment by invoker-LL** [comment]
Sorry for my version updating mistake.
Now I have re-committed the correct version of [Whole_Slide_Bag_FP_SAVE](https://github.com/invoker-LL/WSI-finetuning/blob/e1c6972a3a1fa47b2e3497fb042cbc8a6372431d/datasets/dataset_h5.py#L316).
