### ISSUE TITLE
Inquiry about Complete Code

### ISSUE THREAD

**Issue by bryanwong17** [invoker-LL/WSI-finetuning#6]
Hi, I wonder if you have the complete code in which you combine FT with other methods such as Trans-MIL, DFTD-MIL, Mean-pooling, Max-pooling, and KNN, as shown in the paper. As I believe the current code is only applicable to CLAM.

Thank you!

**Comment by invoker-LL** [comment]
This repository mainly includes the stage-2 fine-tuning by CLAM. In the paper, we report the stage-3 results, which combines the FT feature (by CLAM in this repository) and different WSI head given by other SOTA repository (e.g. [TransMIL](https://github.com/szc19990412/TransMIL), [DTFD](https://github.com/hrzhang1123/DTFD-MIL)).
So, you can just use their provided head and our FT feature to get the result.
I also plan to implement all the strong baselines or SOTA in a unified code in the future and will inform you when the codes open-sourced.

**Comment by bryanwong17** [comment]
Thank you for your answer. Looking forward for the complete code!
