### ISSUE TITLE
Problem in openslide.read_region

### ISSUE THREAD

**Issue by bryanwong17** [invoker-LL/WSI-finetuning#8]
Hi, I encountered a problem while trying to run `extract_topK_ROIs.py`. After debugging, I think the issue lies in the self.wsi.read_region function. Upon checking the OpenSlide documentation, it appears that the coordinates should be specified as x and y. However, when I printed out the coordinates, I found only a single value (e.g., 108736). Could you help me overcome this issue? Thank you!

![image](https://github.com/invoker-LL/WSI-finetuning/assets/67773304/9bc32ae5-eb3d-4ed3-932e-7f22902343a8)
![image](https://github.com/invoker-LL/WSI-finetuning/assets/67773304/9813de3c-605a-4582-b4bb-06bb4055e1d8)

**Comment by invoker-LL** [comment]
The coords should be (x,y) indeed, can you debug the changes of the variable 'self.coords_new'?

**Comment by bryanwong17** [comment]
Here are the outputs of 'self.coords_new':

![image](https://github.com/invoker-LL/WSI-finetuning/assets/67773304/fe94e0cc-b1c3-46e3-b436-95f7c046d289)

![image](https://github.com/invoker-LL/WSI-finetuning/assets/67773304/2f67b899-4fec-4671-a5fa-8d4d707551a4)

**Comment by bryanwong17** [comment]
After checking again, I found out that:

topk_indexes = torch.topk(A.squeeze(), min(args.topk_num, A.shape[0]), sorted=True)[1].cpu()

The dimension of A is always [1, 1024], which makes A.shape[0] always 1. When the code executes min(args.topk_num, A.shape[0]), it proceeds with min(512, 1), resulting in the topk_indices only getting 1 index (e.g., tensor([787])). Do you perhaps know why? Thank you!

**Comment by bryanwong17** [comment]
After checking again, I found out that:

`topk_indexes = torch.topk(A.squeeze(), min(args.topk_num, A.shape[0]), sorted=True)[1].cpu()`

The dimension of A is always [1, 1024], which makes A.shape[0] always 1. When the code executes `min(args.topk_num, A.shape[0])`, it proceeds with min(512, 1), resulting in the topk_indices only getting 1 index (e.g., tensor([787])).

So, from my understanding, when getting the top indices, the condition should be `min(args.topk_num, A.shape[1])`. Please let me know if it is correct. Thank you!

**Comment by invoker-LL** [comment]
You can try A.shape[1]. 
Maybe there is some error in the code, and I will check it and inform you later.
