### ISSUE TITLE
On the Mapping Problem of BRCA Subtype Datasets

### ISSUE THREAD

**Issue by syy-create** [invoker-LL/WSI-finetuning#9]
I noticed that you are using the BRCA dataset in the dataset, so I have a few questions to ask.
1. Has your BRCA dataset been subjected to common subtype binary classification (IDC and ILC).
2. If so, how did you map the labels of IDC and ILC from the BRCA dataset.

**Comment by invoker-LL** [comment]
a) Get it from [here](https://www.cbioportal.org/study/summary?id=brca_tcga_pan_can_atlas_2018).
b) You may also use this [csv](https://github.com/mahmoodlab/MCAT/blob/master/dataset_csv/tcga_brca_all_clean.csv.zip) originally for survival prediction, but there is also the IDC/ILC subtype as:

![brca](https://github.com/invoker-LL/WSI-finetuning/assets/35137989/d6f9971d-cd4f-4b34-a942-f2d0a2f21879)

**Comment by syy-create** [comment]
> a) Get it from [here](https://www.cbioportal.org/study/summary?id=brca_tcga_pan_can_atlas_2018). b) You may also use this [csv](https://github.com/mahmoodlab/MCAT/blob/master/dataset_csv/tcga_brca_all_clean.csv.zip) originally for survival prediction, but there is also the IDC/ILC subtype as:
> 
> ![brca](https://private-user-images.githubusercontent.com/35137989/314070761-d6f9971d-cd4f-4b34-a942-f2d0a2f21879.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NTY0NDEsIm5iZiI6MTcxMDg1NjE0MSwicGF0aCI6Ii8zNTEzNzk4OS8zMTQwNzA3NjEtZDZmOTk3MWQtY2Q0Zi00YjM0LWE5NDItZjJkMGEyZjIxODc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDEzNDkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlZjgwNGEwY2I2MTBmMGJhOTVhMzMwM2JiNDI0NjYwNDU5NGQ1ODQ3NjAyOGQ4NTc3OTQwZTFmODNhYzMzMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WBxSkWiV4BiRtqTpYFamJTf8-PTzP5705uQ-0H0ZXz8)

Thank you very much, it is very useful！
